name: Deploy Program02 to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Program02 to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar el acceso SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Desplegar a cada servidor EC2
      - name: Deploy to EC2 Instance 1
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS1 }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS1 }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/Practice04_Deploy_QA
            git pull origin main
            npm install
            # Usar PM2 para iniciar/reiniciar el servidor
            pm2 start Program02.mjs --name "Practice04" || pm2 restart "Practice04"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 2
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS2 }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS2 }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/Practice04_Deploy_QA
            git pull origin main
            npm install
            pm2 start Program02.mjs --name "Practice04" || pm2 restart "Practice04"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 3
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS3 }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS3 }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/Practice04_Deploy_QA
            git pull origin main
            npm install
            pm2 start Program02.mjs --name "Practice04" || pm2 restart "Practice04"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 4
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS4 }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS4 }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/Practice04_Deploy_QA
            git pull origin main
            npm install
            pm2 start Program02.mjs --name "Practice04" || pm2 restart "Practice04"
            pm2 save
          EOF
