name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      # Deploy to Server 1
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS1 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS1 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y nodejs npm
            node -v
            npm -v
            cd ${{ secrets.TARGET_DIR }}
            nohup node Program02.mjs &
            

      # Deploy to Server 2
      - name: Deploy to Server 2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS2 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands on Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y nodejs npm
            node -v
            npm -v
            cd ${{ secrets.TARGET_DIR }}
            nohup node Program02.mjs &

      # Deploy to Server 3
      - name: Deploy to Server 3
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS3 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands on Server 3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS3 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y nodejs npm
            node -v
            npm -v
            cd ${{ secrets.TARGET_DIR }}
            nohup node Program02.mjs &

        # Deploy to Server 4
      - name: Deploy to Server 4
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS4 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands on Server 4
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS4 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y nodejs npm
            node -v
            npm -v
            cd ${{ secrets.TARGET_DIR }}
            nohup node Program02.mjs &

            